### ISSUE TITLE
Support for Sub Tiers and Prime subscriptions

### ISSUE THREAD

**Issue by d0p3t** [d0p3t/SubNotifier#1]
Integrate new sub tiers and prime subscription messages

**Comment by remcotroost** [comment]
**Added Prime subscriptions in latest commit**
https://github.com/remcotroost/SubNotifier/commit/155d08dfee4484968542b2cbf0c1999324d610cc

**Comment by d0p3t** [comment]
Prime subscriptions is supported now. Subscription tiers will be added in next release

**Comment by d0p3t** [comment]
_**Issue Closed**_

**Prime subscriptions** are now supported. I've decided against notifying sub tiers (see reasoning in comment above).

This issue can be re-opened on a new suggestion to add sub tiers.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10134284-189398152_3-s4-v1.png?transparent=1&palette=1&width=246)
