### ISSUE TITLE
was working fine earlier , now error codes me 

### ISSUE THREAD

**Issue by 6mas** [d0p3t/SubNotifier#13]
was working earlier like 5 hours ago , now when i try start it it gives me https://gyazo.com/02dacf33921895447f596b57df6c66ea

**Comment by d0p3t** [comment]
run it like this

`npm run build && npm run serve`

**Comment by 6mas** [comment]
no that didnt do anything https://gyazo.com/8f8cc27fd8932453a5b1bfcb73b840ca

**Comment by d0p3t** [comment]
You are on Windows.

1. `npm run build`
2. `npm run serve`

**Comment by 6mas** [comment]
https://gyazo.com/0dad705eff20db52f9cf520d44736307

**Comment by 6mas** [comment]
ok found the problem , i deleted one of the channels from the top where it says channels and left just the # , i was trying to disable it from going into the chat till i wanted it to go into that
