### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by MrBlazie** [d0p3t/SubNotifier#14]
Hello, I just followed all the steps for the SubNotifier and i ran into a few problems.
After running the "npm start" this happens: https://gyazo.com/986adba84823f68e2c069e98da0cb004

**Comment by d0p3t** [comment]
Please have a look at issue #13 . Your config is probably wrong

**Comment by MrBlazie** [comment]
Okay so my token part was wrong. But now when i try to do the /me it doesnt work on the twitch chat end https://gyazo.com/bfd159335702bded3f523474404c6ff4

**Comment by MrBlazie** [comment]
Also is there a way for it to spam the same message for 3 lines of chat?

**Comment by d0p3t** [comment]
If you set 
```js
enableMeMode: true,
```
in the config, it will use /me

No, you cannot write multiple lines at once.
