### ISSUE TITLE
At the end, it says (null)

### ISSUE THREAD

**Issue by Lyvondria** [d0p3t/SubNotifier#3]
Hello,

I got a problem. This script works fine. But at the end of every Sub/resub message, it says (null). Example:

Lyvondria has just subscribed!(null)

Am I doing something wrong? I only changed the resub message.

**Comment by d0p3t** [comment]
This was due to changes with TwitchNotify. 
* `message` was removed from default subscription notify in commit a1ed2bc376949bb404555953c970340982dc7cee

**Closed**

**Comment by d0p3t** [comment]
Still an issue with `message`. Also happens during resubscriptions. Requires more debugging

**Comment by d0p3t** [comment]
* Added check to see whether `message === null`

This addition fixes the bug when the message would be displayed as null in chat. This was due to a viewer not being required to enter a message.

See b09693ab3824233f8bbf4ddeb5ccc938308a647b
