### ISSUE TITLE
Change `npm start`

### ISSUE THREAD

**Issue by d0p3t** [d0p3t/SubNotifier#37]
`npm start` will not work if one isn't using the release version.

Should change this. Perhaps create a separate startup script for the release. The updated version created confusion with users. 

```bash
// start.cmd/sh
node index.js
```

**Comment by olthoi** [comment]
Hi,
       So I believe I setup everything correctly but I keep getting errors, here's the error log. Any ideas how to fix this?
[2019-04-21T00_31_33_390Z-debug.log](https://github.com/d0p3t/SubNotifier/files/3100743/2019-04-21T00_31_33_390Z-debug.log)

**Comment by d0p3t** [comment]
There have been ennough new versions that this shouldn't be an issue anymore. It works as intended
