### ISSUE TITLE
Bug: All resubs show incorrect number

### ISSUE THREAD

**Issue by mmt-itns** [d0p3t/SubNotifier#38]
Hi,

I'm using the latest version, but on all resubs we get 0 months despite how long it is. Is there a fix for this?

The log shows like this:

{"message":"RESUBALERT was sent to channel: #x for username: y [ 0 months ]","level":"info"}

**Comment by d0p3t** [comment]
Thank you for the report. This is probably due to the recent changes from
Twitch regarding sub badges / resub months.

I will investigate this and report back to you

**Comment by d0p3t** [comment]
This bug is due to deprecated Twitch API. See https://github.com/tmijs/tmi.js/issues/325

**Comment by mja00** [comment]
tmi.js fixed this issue in 1.4

**Comment by d0p3t** [comment]
Thank you. I just saw that it was indeed addressed. Unfortunately, they have not yet updated their npm package, so we will have to wait until they do so.

**Comment by mja00** [comment]
Hate being up your ass, I know the feeling I've got like 3 people up my ass currently. But right as you sent this reply they updated their npm package. I love your script because it just works so well. I'd update it myself if I knew how lmao.

**Comment by d0p3t** [comment]
I have reverted to using `tmi.js` over `twitch-js` as that package has not been updated for 3 months. See 65ac5657294757762291fd1e8af71bd855b3d6aa

Please let me know if this fixes the issue as I am unable to test this myself

**Comment by mja00** [comment]
![image](https://user-images.githubusercontent.com/11252574/53774632-4c382600-3ebd-11e9-8561-7f02120feab5.png)
Still shows as 0 months
