### ISSUE TITLE
Adding log file if someone subscribe

### ISSUE THREAD

**Issue by Lyvondria** [d0p3t/SubNotifier#4]
Would be cool if when someone subscribed, it will create a log folder or a log file where some informations are stored like timstamps when he subscribed e.g

**Comment by Lyvondria** [comment]
Also, would be cool to add in the console where the sub happened when someone subed. example: Resub Prime -> nameofchannel

**Comment by d0p3t** [comment]
I do want to keep this script simple as it's just meant to chat whenever someone subscribes or resubscribes, but I will add simple file and console logging

**Comment by d0p3t** [comment]
* Added a logfile that logs all subscriptions and resubscriptions
* Information sent to logfile is also visible in console

See b09693ab3824233f8bbf4ddeb5ccc938308a647b
