### ISSUE TITLE
Gifted subs show name as 0

### ISSUE THREAD

**Issue by mmt-itns** [d0p3t/SubNotifier#40]
Hi,

As per title, when gifting a sub now (On latest version from #38 v1.0.9) gifting a sub now shows like:

Thanks for gifting a sub to 0 *subgifter*

I'm not sure if this is related to the fix per #38 regarding resubs showing as 0 months.

**Comment by d0p3t** [comment]
This might indeed be related to #38 , specifically the change to the Twitch API. I will look at this this weekend.

**Comment by mja00** [comment]
I'm testing a fix right now. Got it implemented just waiting for someone to gift a sub in my test channel.

**Comment by mja00** [comment]
Tried many different fixes to no help. Reset the code to what it was before. Started working all of a sudden... I have no clue.

**Comment by d0p3t** [comment]
Is this still an issue? 🤔

**Comment by 6mas** [comment]
not an issue for me, looks fixed now

**Comment by katasuno** [comment]
I solved it as follows.
Before;
![image](https://user-images.githubusercontent.com/62215083/104137943-a788a880-53b1-11eb-8030-e0b8e82ffdd5.png)

After;
![image](https://user-images.githubusercontent.com/62215083/104137962-d6068380-53b1-11eb-9b99-6452ace715af.png)

I saw this in order in Tmi.js, you should pay attention to this order!
