### ISSUE TITLE
[Suggestion] Support for bits

### ISSUE THREAD

**Issue by ChilliHam** [d0p3t/SubNotifier#5]
Not sure if its possible but maybe have it set to a minimum number of bits?

**Comment by d0p3t** [comment]
Support for Bits would be a new feature and require me to stray away from the simplicity of this tool.

However, I am open for such enhancements as long as they stay within the scope of notifying chat about an events like new subscriptions, followers, bits.

I'll think about adding this. Thank you for your suggestion

![bitmoji](https://render.bitstrips.com/v2/cpanel/7834193-189398152_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by d0p3t** [comment]
_**Update:** I've started refactoring the whole codebase and also including support for bits. Expect an update by the end of 12 September._ 

You can read more about it in issue #6

**Comment by d0p3t** [comment]
I've added support for bits.

Commit 009b34f

Thank you again for your suggestion.
![bitmoji](https://render.bitstrips.com/v2/cpanel/7638212-189398152_3-s4-v1.png?transparent=1&palette=1&width=246)

Now closed.
